// --- Initial Data ---
export const initialFxRate = 1580.0;

export const defaultBanks = [
  "Access Bank Plc",
  "First Bank of Nigeria",
  "Zenith Bank Plc",
  "GTBank Plc",
  "UBA Plc",
  "Stanbic IBTC Bank",
  "FCMB",
  "Polaris Bank",
];

export const defaultSubsidiaries = [
  "Corporate Office",
  "Sales & Marketing",
  "Operations",
  "Finance & Admin",
  "IT & Digital",
  "Supply Chain",
  "Human Resources",
];

export const initialCurrencies = [
  { code: "NGN", rate: 1 },
  { code: "USD", rate: initialFxRate },
];

export const initialFacilities = [
  {
    id: "F001",
    bank: "Access Bank Plc",
    facilityName: "Working Capital Facility",
    ccy: "NGN",
    limitF: 2000000000,
    facilityAmount: 1800000000,
    startDate: "2024-01-15",
    maturity: "2025-02-01",
    tenureValue: 12,
    tenureUnit: "Months",
    tenure2Value: 0,
    tenure2Unit: "Months",
    intPayCycle: "Monthly",
    repCycle: "Bullet",
    maxCycleValue: 24,
    maxCycleUnit: "Months",
    boardRate: 19.0,
    mgmtFee: 1.0,
    commitFee: 0.5,
    defaultInt: 24.0,
    moratoriumValue: 3,
    moratoriumUnit: "Months",
    collateral: "Corporate Guarantee",
    remarks: "Renewable annually",
    facilityClass: "Term Loan",
    offeredRate: 21.0,
    negFixedRate: 18.5,
    confirmed: "Yes",
    confirmDate: "2024-02-01",
    status: "Active",
    interestRateType: "Fixed",
    pricingFormula: "Benchmark + 3%",
    interestBasis: "Daily/Simple",
    drawdowns: [
      {
        id: "D001",
        date: "2024-03-01",
        amount: 1000000000,
        purpose: "Working Capital",
        repaid: 0,
        subsidiary: "Corporate Office",
        interestRateOverride: null,
        marginApplied: false,
        marginRate: 0,
        subFacility: "primary",
        subsidiaryRepaid: 0,
      },
    ],
  },
  {
    id: "F002",
    bank: "First Bank of Nigeria",
    facilityName: "Import Finance Facility",
    ccy: "USD",
    limitF: 5000000,
    facilityAmount: 4500000,
    startDate: "2024-03-10",
    maturity: "2024-09-15",
    tenureValue: 6,
    tenureUnit: "Months",
    tenure2Value: 0,
    tenure2Unit: "Months",
    intPayCycle: "Quarterly",
    repCycle: "Bullet",
    maxCycleValue: 12,
    maxCycleUnit: "Months",
    boardRate: 8.0,
    mgmtFee: 0.5,
    commitFee: 0.35,
    defaultInt: 15.0,
    moratoriumValue: 0,
    moratoriumUnit: "None",
    collateral: "Fixed Charge over Assets",
    remarks: "Linked to LC issuance",
    facilityClass: "Trade Finance",
    offeredRate: 9.0,
    negFixedRate: 7.5,
    confirmed: "Yes",
    confirmDate: "2024-03-15",
    status: "Active",
    interestRateType: "Fixed",
    pricingFormula: "Benchmark + 2%",
    interestBasis: "Daily/Simple",
    drawdowns: [
      {
        id: "D002",
        date: "2024-04-01",
        amount: 3000000,
        purpose: "Import Finance",
        repaid: 0,
        subsidiary: "Supply Chain",
        interestRateOverride: null,
        marginApplied: false,
        marginRate: 0,
        subFacility: "primary",
        subsidiaryRepaid: 0,
      },
    ],
  },
  {
    id: "F003",
    bank: "Zenith Bank Plc",
    facilityName: "Term Loan Facility",
    ccy: "NGN",
    limitF: 5000000000,
    facilityAmount: 4800000000,
    startDate: "2023-10-15",
    maturity: "2025-05-01",
    tenureValue: 18,
    tenureUnit: "Months",
    tenure2Value: 0,
    tenure2Unit: "Months",
    intPayCycle: "Monthly",
    repCycle: "Quarterly",
    maxCycleValue: 36,
    maxCycleUnit: "Months",
    boardRate: 19.5,
    mgmtFee: 1.5,
    commitFee: 0.75,
    defaultInt: 26.0,
    moratoriumValue: 6,
    moratoriumUnit: "Months",
    collateral: "Debenture + Equity Pledge",
    remarks: "Board resolution required",
    facilityClass: "Term Loan",
    offeredRate: 22.0,
    negFixedRate: 19.0,
    confirmed: "Yes",
    confirmDate: "2023-11-01",
    status: "Active",
    interestRateType: "Fixed",
    pricingFormula: "Benchmark + 4%",
    interestBasis: "Daily/Simple",
    drawdowns: [
      {
        id: "D003",
        date: "2024-01-01",
        amount: 3000000000,
        purpose: "Capital Expansion",
        repaid: 500000000,
        subsidiary: "Operations",
        interestRateOverride: null,
        marginApplied: false,
        marginRate: 0,
        subFacility: "primary",
        subsidiaryRepaid: 0,
      },
    ],
  },
];